# Site settings
title: "Siegfried Sahuc"
description: "Recherche d'un contrat d'apprentissage de 2 ans pour un poste en Architecture des Logiciels"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Siegfried Sahuc"
resume_title:                   "Recherche d'un apprentissage de 2 ans"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "siegfriedsahuc+job@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "06.61.74.73.47"
resume_contact_address:         "11 rue d'Annam, Paris"

resume_header_contact_info:     "11 rue d'Annam, Paris • 06.61.74.73.47 • siegfriedsahuc@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Dans le cadre d'un Mastère Architecture des Logiciels, je recherhe un contrat d'apprentissage avec un rythme de 3 semaines en entreprise et 1 semaine en formation. Je suis disponible à partir d'Octobre 2021 </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/SiegfriedShc"
 # resume_twitter_url:           "http://twitter.com/jglovier"
 # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/siegfried-sahuc-0589b712b"
  # resume_instagram_url:         "insert your Instagram URL here"
 # resume_website_url:           "http://joelglovier.com"
 # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
